# Generated by Django 5.1.7 on 2025-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_category', models.CharField(blank=True, choices=[('APPLES', 'Apples'), ('ORANGES', 'Oranges'), ('STRAWBERRY', 'Strawberry'), ('BANANA', 'Banana'), ('PUMPKIN', 'Pumpkin'), ('VEGETABLE', 'Vegetable')], max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
