# Generated by Django 5.1.7 on 2025-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_price', models.CharField(blank=True, max_length=10, null=True)),
                ('product_category', models.CharField(blank=True, choices=[('Apples', 'Apples'), ('Oranges', 'Oranges'), ('Strawberries', 'Strawberries'), ('Bananas', 'Bananas'), ('Pumpkins', 'Pumpkins'), ('Vegetables', 'Vegetables')], max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
