# Generated by Django 5.1.7 on 2025-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
