# Generated by Django 5.1.7 on 2025-03-18 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Apples', 'Apples'), ('Oranges', 'Oranges'), ('Strawberries', 'Strawberries'), ('Bananas', 'Bananas'), ('Pumpkins', 'Pumpkins'), ('Vegetables', 'Vegetables')], max_length=255, null=True),
        ),
    ]
