# Generated by Django 5.1.7 on 2025-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cartitem_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=9),
        ),
    ]
