# Generated by Django 5.1.7 on 2025-03-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_cart_user_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='web.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
