"""
Django settings for fruitable project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'web',
    'accounts',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

# Ckeditor config
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link',
                'bulletedList', 'numberedList', 'todoList', 'blockQuote', 'imageUpload',
                '|', 'codeBlock', 'sourceEditing', 'insertImage', 'mediaEmbed', 'insertTable',
                '|', 'undo', 'redo', 'removeFormat', 'alignment', 'fontSize', 'fontFamily',
                'fontColor', 'fontBackgroundColor', 'highlight', 'horizontalLine',
                'specialCharacters', 'subscript', 'superscript', 'findAndReplace',
                'indent', 'outdent', 'pageBreak', 'exportPdf', 'exportWord', '|',
                'trackChanges', 'comment', 'mention', 'wordCount', 'autosave'
            ],
            'shouldNotGroupWhenFull': True
        }
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3', '|',
            'bulletedList', 'numberedList', '|', 'blockQuote'
        ],
        'toolbar': {
            'items': [
                'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link',
                'underline', 'strikethrough', 'code', 'subscript', 'superscript', 'highlight',
                '|', 'codeBlock', 'sourceEditing', 'insertImage', 'bulletedList',
                'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed',
                'removeFormat', 'insertTable', '|', 'undo', 'redo', '|', 'findAndReplace',
                'horizontalLine', 'specialCharacters', 'mention', 'wordCount', 'autosave',
                'alignment', 'pageBreak', 'exportPdf', 'exportWord', '|', 'trackChanges', 'comment'
            ],
            'shouldNotGroupWhenFull': True
        },
        'alignment': {
            'options': ['left', 'right', 'center', 'justify']
        },
        'fontSize': {
            'options': ['tiny', 'small', 'default', 'big', 'huge'],
            'supportAllValues': True
        },
        'fontFamily': {
            'options': ['Arial', 'Courier New', 'Georgia', 'Times New Roman', 'Verdana']
        },
        'fontColor': {
            'columns': 6,
            'documentColors': 12
        },
        'fontBackgroundColor': {
            'columns': 6,
            'documentColors': 12
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|', 'imageStyle:alignLeft',
                'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|',
                'imageResize'
            ],
            'styles': ['full', 'side', 'alignLeft', 'alignRight', 'alignCenter'],
            'resizeUnit': 'px'
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ]
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1',
                 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2',
                 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3',
                 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        },
        'autosave': {
            'save': "editor => { "
            "localStorage.setItem('editorContent',"
            "editor.getData()); console.log('Content saved to local storage'); }"
        },
        'wordCount': {
            'displayWords': True,
            'displayCharacters': True
        },
        'pasteFromOffice': {
            'enabled': True
        },
        'exportPdf': {
            'stylesheets': [
              'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css']
        },
        'exportWord': {
            'stylesheets': [
              'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css']
        },
        'trackChanges': {
            'enabled': True
        },
        'comment': {
            'enabled': True
        }
    }
}

ROOT_URLCONF = 'fruitable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processor.cart_count_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'fruitable.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Looking to send emails in production? Check out our Email API/SMTP product!
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = env('EMAIL_PORT')
